# 작업형 제 2유형 예시문제

### ※ 본 시험가이드는, 빅데이터분석기사 실기시험 응시를 준비하시는 "초보자"분들을 위해 고득점이 아닌 "평균점수" 취득을 목표로 제작했습니다.

### 1. 데이터 로드
만약, 한글이 깨지면 encoding = "euc-kr"
데이터 프레임이 잘 읽어졌는지 확인한다.

### 2. 데이터 전처리 및 EDA

※이때, 전처리는 train data와 test data 동시에 처리해 주어야 한다.※

- isnull().sum()을 이용해서 결측값을 확인하고
결측값이 존재하면, 결측값이 존재하는 컬럼을 확인하고, 해당 컬럼의 정보를 .describe() 메서드로 확인해본다.

- 데이터 타입을 확인한다.
sklearn의 대부분의 모델은 object 형 data를 입력값으로 허락하지 않는다. 따라서 object dtypes을 그대로 사용하면, error가 발생한다.

- 형변환을 해주어야 한다.
대표적으로는 LabelEncoding과 OnehotEncoding이 있다. 원-핫 인코딩은 Pandas의 get_dummies() 함수로도 구현 가능)
원-핫 인코딩을 할 때에는, 컬럼의 유일값이 너무 많지는 않은지 확인할 필요가 있다. 유일값이 너무 많으면 df가 커져서 성능이 떨어짐. 

- 결측값 처리를 해준다.
앞서 결측값을 확인했을 떄, 결측값이 존재하는 행을 drop하거나 0으로 대치하거나, 평균값으로 대치하거나 등등 각 상황에 맞게 하면 된다

### 3. EDA
EDA과정은 Data Scientist의 역량에 따라 다르게 진행되므로, 설명은 생략하겠다.
EDA과정을 거친 후, 

- 모델학습에 사용할 Fearture를 선정하고 리스트를 만들어둔다.

- 모델검증을 할 수 있도록 train_x와 trian_y를 train_test_split을 이용하여 train_x,y과 valid_x,y로 분할 해준다.

### 4. 모델링 단계
분류문제인지, 회귀문제인지 등등을 고려하여 모델을 구성한다.(파이프라인 등을 다양하게 적용)

### 5.모델 학습 , 모델 평가, Target 예측 단계
구성한 모델에 train data set을 적합시킨다.
적합된 모델을 valid set을 이용하여 검증한다. (이때, 평가척도는 개인이 유동적으로 선택)

검증이 완료된 모델로 test_x data에 대한 target을 예측한다.

### 6. 제출파일을 생성



※데이터분석은 정해진 방법이 없습니다. 개인 역량이 중요합니다. 

### 해당 노트북 Upvote와 깃 저장소 "Star"클릭 부탁드립니다.



### 데이터 로드

In [1]:
import pandas as pd

x_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/dataq/main/X_train.csv", encoding = 'euc-kr')
y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/dataq/main/y_train.csv")
x_test = pd.read_csv("https://raw.githubusercontent.com/Datamanim/dataq/main/X_test.csv", encoding = 'euc-kr')

In [2]:
x_train.set_index(x_train['cust_id'], inplace=True) # 인덱스의 첫 컬럼을 인덱스로 사용
y_train.set_index(y_train['cust_id'], inplace=True)
x_test.set_index(x_test['cust_id'], inplace=True)

In [3]:
x_train

cust_id       총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수  \
cust_id                                                                
0              0   68282840  11264000  6860000.0      기타   강남점    19   
1              1    2136000   2136000   300000.0     스포츠   잠실점     2   
2              2    3197000   1639000        NaN  남성 캐주얼   관악점     2   
3              3   16077620   4935000        NaN      기타   광주점    18   
4              4   29050000  24000000        NaN      보석  본  점     2   
...          ...        ...       ...        ...     ...   ...   ...   
3495        3495    3175200   3042900        NaN      골프  본  점     1   
3496        3496   29628600   7200000  6049600.0    시티웨어  부산본점     8   
3497        3497      75000     75000        NaN    주방용품   창원점     1   
3498        3498    1875000   1000000        NaN     화장품  본  점     2   
3499        3499  263101550  34632000  5973000.0      기타  본  점    38   

          내점당구매건수    주말방문비율  구매주기  
cust_id                            
0        3.894737  0.527027    17  
1        1.500000  0.000000     1  
2        2.000000  0.000000     1  
3        2.444444  0.318182    16  
4        1.500000  0.000000    85  
...           ...       ...   ...  
3495     2.000000  1.000000     0  
3496     1.625000  0.461538    40  
3497     1.000000  0.000000     0  
3498     1.000000  0.000000    39  
3499     2.421053  0.467391     8  

[3500 rows x 10 columns]

In [4]:
y_train

cust_id  gender
cust_id                 
0              0       0
1              1       0
2              2       1
3              3       1
4              4       0
...          ...     ...
3495        3495       1
3496        3496       1
3497        3497       0
3498        3498       0
3499        3499       0

[3500 rows x 2 columns]

In [5]:
x_test

cust_id       총구매액     최대구매액        환불금액   주구매상품 주구매지점  내점일수  \
cust_id                                                                 
3500        3500   70900400  22000000   4050000.0      골프  부산본점    13   
3501        3501  310533100  38558000  48034700.0     농산물   잠실점    90   
3502        3502  305264140  14825000  30521000.0    가공식품  본  점   101   
3503        3503    7594080   5225000         NaN    주방용품  부산본점     5   
3504        3504    1795790   1411200         NaN     수산품  청량리점     3   
...          ...        ...       ...         ...     ...   ...   ...   
5977        5977   82581500  23976000         NaN      골프  부산본점     8   
5978        5978     480000    480000         NaN    섬유잡화   광주점     1   
5979        5979  260003790  25750000         NaN  남성 캐주얼  본  점    19   
5980        5980   88991520  18120000         NaN      육류  본  점     5   
5981        5981     623700    209000         NaN    가공식품  영등포점     2   

           내점당구매건수    주말방문비율  구매주기  
cust_id                             
3500      1.461538  0.789474    26  
3501      2.433333  0.369863     3  
3502     14.623762  0.083277     3  
3503      2.000000  0.000000    47  
3504      2.666667  0.125000     8  
...            ...       ...   ...  
5977      1.750000  0.642857    40  
5978      1.000000  0.000000     0  
5979      3.736842  0.915493    18  
5980      3.600000  0.444444    60  
5981      5.000000  0.000000    31  

[2482 rows x 10 columns]

### 데이터 전처리 및 EDA

x_test data 결측값 확인

In [6]:
x_test.isnull().sum()

cust_id       0
총구매액          0
최대구매액         0
환불금액       1611
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
dtype: int64

x_test data 결측값 컬럼 정보 확인

In [7]:
x_test['환불금액'].describe()

count    8.710000e+02
mean     2.554716e+07
std      5.944074e+07
min      1.000000e+04
25%      2.414000e+06
50%      8.100000e+06
75%      2.228090e+07
max      8.715144e+08
Name: 환불금액, dtype: float64

 x_train data의 결측값 확인

In [8]:
x_train.isnull().sum()

cust_id       0
총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
dtype: int64

x_train data 결측값 컬럼 정보 확인

In [9]:
x_train['환불금액'].describe()

count    1.205000e+03
mean     2.407822e+07
std      4.746453e+07
min      5.600000e+03
25%      2.259000e+06
50%      7.392000e+06
75%      2.412000e+07
max      5.637530e+08
Name: 환불금액, dtype: float64

x_test data와 x_train data의  환불금액 컬럼의 결측값을 0으로 변환

In [10]:
x_test['환불금액'] = x_test['환불금액'].fillna(0)
x_train['환불금액'] = x_train['환불금액'].fillna(0)

In [11]:
x_test.isnull().sum()

cust_id    0
총구매액       0
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
내점일수       0
내점당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64

In [12]:
x_train.isnull().sum()

cust_id    0
총구매액       0
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
내점일수       0
내점당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64

데이터의 데이터 타입 확인

In [13]:
x_test.dtypes

cust_id      int64
총구매액         int64
최대구매액        int64
환불금액       float64
주구매상품       object
주구매지점       object
내점일수         int64
내점당구매건수    float64
주말방문비율     float64
구매주기         int64
dtype: object

In [14]:
x_train.dtypes

cust_id      int64
총구매액         int64
최대구매액        int64
환불금액       float64
주구매상품       object
주구매지점       object
내점일수         int64
내점당구매건수    float64
주말방문비율     float64
구매주기         int64
dtype: object

object데이터는 모델학습에 사용하려면 변환해 주어야함.

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
x_train.loc[:,['주구매상품', '주구매지점']] = x_train.loc[:,['주구매상품', '주구매지점']].apply(LabelEncoder().fit_transform)
x_test.loc[:,['주구매상품', '주구매지점']] = x_test.loc[:,['주구매상품', '주구매지점']].apply(LabelEncoder().fit_transform)

데이터 타입 변환됐는지 확인해본다.

In [17]:
x_test.dtypes

cust_id      int64
총구매액         int64
최대구매액        int64
환불금액       float64
주구매상품        int64
주구매지점        int64
내점일수         int64
내점당구매건수    float64
주말방문비율     float64
구매주기         int64
dtype: object

### 모델학습에 사용할 피쳐 지정

In [18]:
features = ['총구매액', '최대구매액', '환불금액', '주구매상품', '주구매지점', '내점일수', '내점당구매건수', '주말방문비율', '구매주기']

In [19]:
X = x_train[features]

In [20]:
X

총구매액     최대구매액       환불금액  주구매상품  주구매지점  내점일수   내점당구매건수  \
cust_id                                                                 
0         68282840  11264000  6860000.0      5      0    19  3.894737   
1          2136000   2136000   300000.0     21     19     2  1.500000   
2          3197000   1639000        0.0      6      1     2  2.000000   
3         16077620   4935000        0.0      5      2    18  2.444444   
4         29050000  24000000        0.0     15      8     2  1.500000   
...            ...       ...        ...    ...    ...   ...       ...   
3495       3175200   3042900        0.0      3      8     1  2.000000   
3496      29628600   7200000  6049600.0     22      9     8  1.625000   
3497         75000     75000        0.0     32     21     1  1.000000   
3498       1875000   1000000        0.0     41      8     2  1.000000   
3499     263101550  34632000  5973000.0      5      8    38  2.421053   

           주말방문비율  구매주기  
cust_id                  
0        0.527027    17  
1        0.000000     1  
2        0.000000     1  
3        0.318182    16  
4        0.000000    85  
...           ...   ...  
3495     1.000000     0  
3496     0.461538    40  
3497     0.000000     0  
3498     0.000000    39  
3499     0.467391     8  

[3500 rows x 9 columns]

In [21]:
Y = y_train['gender']

In [22]:
Y

cust_id
0       0
1       0
2       1
3       1
4       0
       ..
3495    1
3496    1
3497    0
3498    0
3499    0
Name: gender, Length: 3500, dtype: int64

In [23]:
x_test[features] #x_test data는 학습에 사용하지 않음

총구매액     최대구매액        환불금액  주구매상품  주구매지점  내점일수    내점당구매건수  \
cust_id                                                                   
3500      70900400  22000000   4050000.0      3      9    13   1.461538   
3501     310533100  38558000  48034700.0      9     19    90   2.433333   
3502     305264140  14825000  30521000.0      0      8   101  14.623762   
3503       7594080   5225000         0.0     31      9     5   2.000000   
3504       1795790   1411200         0.0     19     22     3   2.666667   
...            ...       ...         ...    ...    ...   ...        ...   
5977      82581500  23976000         0.0      3      9     8   1.750000   
5978        480000    480000         0.0     17      2     1   1.000000   
5979     260003790  25750000         0.0      6      8    19   3.736842   
5980      88991520  18120000         0.0     26      8     5   3.600000   
5981        623700    209000         0.0      0     15     2   5.000000   

           주말방문비율  구매주기  
cust_id                  
3500     0.789474    26  
3501     0.369863     3  
3502     0.083277     3  
3503     0.000000    47  
3504     0.125000     8  
...           ...   ...  
5977     0.642857    40  
5978     0.000000     0  
5979     0.915493    18  
5980     0.444444    60  
5981     0.000000    31  

[2482 rows x 9 columns]

### 학습셋과 검증셋을 분리

In [24]:
from sklearn.model_selection import train_test_split

'''
import numpy as np
    >>> from sklearn.model_selection import train_test_split
    >>> X, y = np.arange(10).reshape((5, 2)), range(5)
    >>> X
    array([[0, 1],
           [2, 3],
           [4, 5],
           [6, 7],
           [8, 9]])
    >>> list(y)
    [0, 1, 2, 3, 4]
    
    >>> X_train, X_test, y_train, y_test = train_test_split(
    ...     X, y, test_size=0.33, random_state=42)
    ...
    >>> X_train
    array([[4, 5],
           [0, 1],
           [6, 7]])
    >>> y_train
    [2, 0, 3]
    >>> X_test
    array([[2, 3],
           [8, 9]])
    >>> y_test
    [1, 4]
    
    >>> train_test_split(y, shuffle=False)
    [[0, 1, 2], [3, 4]]
    '''

'\nimport numpy as np\n    >>> from sklearn.model_selection import train_test_split\n    >>> X, y = np.arange(10).reshape((5, 2)), range(5)\n    >>> X\n    array([[0, 1],\n           [2, 3],\n           [4, 5],\n           [6, 7],\n           [8, 9]])\n    >>> list(y)\n    [0, 1, 2, 3, 4]\n    \n    >>> X_train, X_test, y_train, y_test = train_test_split(\n    ...     X, y, test_size=0.33, random_state=42)\n    ...\n    >>> X_train\n    array([[4, 5],\n           [0, 1],\n           [6, 7]])\n    >>> y_train\n    [2, 0, 3]\n    >>> X_test\n    array([[2, 3],\n           [8, 9]])\n    >>> y_test\n    [1, 4]\n    \n    >>> train_test_split(y, shuffle=False)\n    [[0, 1, 2], [3, 4]]\n    '

In [25]:
import numpy as np

x_train, x_valid, y_train, y_valid = train_test_split(X, Y, random_state=0)

In [26]:
x_train

총구매액     최대구매액        환불금액  주구매상품  주구매지점  내점일수   내점당구매건수  \
cust_id                                                                  
1410       1560000   1495000         0.0     12     15     1  2.000000   
1310       4832810    980000   2411200.0      0      1    13  5.384615   
2140      58564760  21408000  69635400.0      0      8    36  2.472222   
3332       8963000   1817000         0.0      5      7     8  2.875000   
1002        789500    375000         0.0     17     10     1  5.000000   
...            ...       ...         ...    ...    ...   ...       ...   
835      109913260  16566000         0.0     41      9    30  2.500000   
3264      61579900  10800000         0.0      0     19    15  1.866667   
1653       3200500   1728000         0.0      0      8     4  2.000000   
2607       9200000   6800000   4290000.0     11     19     3  1.333333   
2732      42411480  23989000         0.0      0      8     4  3.750000   

           주말방문비율  구매주기  
cust_id                  
1410     0.000000     0  
1310     0.157143    24  
2140     0.157303     9  
3332     0.434783    28  
1002     1.000000     0  
...           ...   ...  
835      0.493333    12  
3264     0.071429    21  
1653     0.500000    85  
2607     0.000000    19  
2732     0.000000    70  

[2625 rows x 9 columns]

In [27]:
x_valid

총구매액      최대구매액         환불금액  주구매상품  주구매지점  내점일수   내점당구매건수  \
cust_id                                                                    
1269       3303000    2772000          0.0     21     15     1  5.000000   
118      228654470   30000000   45308500.0      5      3    69  2.681159   
2809       2161400    1982400          0.0      0     18     2  3.500000   
2620     140784680   32366400     667000.0      3      9    20  2.100000   
1535      27157530   14160000          0.0      5      0     7  3.000000   
...            ...        ...          ...    ...    ...   ...       ...   
1427     158728320   39960000          0.0      2      8     9  1.444444   
674      933509250  121072000  161372000.0     24     18    53  2.094340   
454       86248600    9680000    3886000.0     24      8    30  2.266667   
1052     108406350    9255000   31777200.0     24      9    39  3.025641   
722      288517600   32850000   15150000.0      5     19    84  4.428571   

           주말방문비율  구매주기  
cust_id                  
1269     0.000000     0  
118      0.248649     5  
2809     0.000000     0  
2620     0.595238    16  
1535     0.523810    34  
...           ...   ...  
1427     0.153846    37  
674      0.738739     6  
454      0.147059    11  
1052     0.254237     8  
722      0.309140     4  

[875 rows x 9 columns]

### 모델링

In [28]:
from sklearn.ensemble import RandomForestClassifier
'''
Examples
 |  --------
 |  >>> from sklearn.ensemble import RandomForestClassifier
 |  >>> from sklearn.datasets import make_classification
 |  >>> X, y = make_classification(n_samples=1000, n_features=4,
 |  ...                            n_informative=2, n_redundant=0,
 |  ...                            random_state=0, shuffle=False)
 |  >>> clf = RandomForestClassifier(max_depth=2, random_state=0)
 |  >>> clf.fit(X, y)
 |  RandomForestClassifier(...)
 |  >>> print(clf.predict([[0, 0, 0, 0]]))
 |  [1]
 '''

'\nExamples\n |  --------\n |  >>> from sklearn.ensemble import RandomForestClassifier\n |  >>> from sklearn.datasets import make_classification\n |  >>> X, y = make_classification(n_samples=1000, n_features=4,\n |  ...                            n_informative=2, n_redundant=0,\n |  ...                            random_state=0, shuffle=False)\n |  >>> clf = RandomForestClassifier(max_depth=2, random_state=0)\n |  >>> clf.fit(X, y)\n |  RandomForestClassifier(...)\n |  >>> print(clf.predict([[0, 0, 0, 0]]))\n |  [1]\n '

In [29]:
x_train

총구매액     최대구매액        환불금액  주구매상품  주구매지점  내점일수   내점당구매건수  \
cust_id                                                                  
1410       1560000   1495000         0.0     12     15     1  2.000000   
1310       4832810    980000   2411200.0      0      1    13  5.384615   
2140      58564760  21408000  69635400.0      0      8    36  2.472222   
3332       8963000   1817000         0.0      5      7     8  2.875000   
1002        789500    375000         0.0     17     10     1  5.000000   
...            ...       ...         ...    ...    ...   ...       ...   
835      109913260  16566000         0.0     41      9    30  2.500000   
3264      61579900  10800000         0.0      0     19    15  1.866667   
1653       3200500   1728000         0.0      0      8     4  2.000000   
2607       9200000   6800000   4290000.0     11     19     3  1.333333   
2732      42411480  23989000         0.0      0      8     4  3.750000   

           주말방문비율  구매주기  
cust_id                  
1410     0.000000     0  
1310     0.157143    24  
2140     0.157303     9  
3332     0.434783    28  
1002     1.000000     0  
...           ...   ...  
835      0.493333    12  
3264     0.071429    21  
1653     0.500000    85  
2607     0.000000    19  
2732     0.000000    70  

[2625 rows x 9 columns]

In [30]:
y_train

cust_id
1410    0
1310    0
2140    0
3332    1
1002    0
       ..
835     0
3264    0
1653    1
2607    0
2732    1
Name: gender, Length: 2625, dtype: int64

In [31]:
case = RandomForestClassifier(max_depth=5, random_state=0)

In [32]:
case = RandomForestClassifier(random_state = 0)

In [33]:
case.fit(x_train, y_train)

RandomForestClassifier(random_state=0)

### 모델 검증

In [34]:
valid_pred = case.predict(x_valid)

In [35]:
x_valid

총구매액      최대구매액         환불금액  주구매상품  주구매지점  내점일수   내점당구매건수  \
cust_id                                                                    
1269       3303000    2772000          0.0     21     15     1  5.000000   
118      228654470   30000000   45308500.0      5      3    69  2.681159   
2809       2161400    1982400          0.0      0     18     2  3.500000   
2620     140784680   32366400     667000.0      3      9    20  2.100000   
1535      27157530   14160000          0.0      5      0     7  3.000000   
...            ...        ...          ...    ...    ...   ...       ...   
1427     158728320   39960000          0.0      2      8     9  1.444444   
674      933509250  121072000  161372000.0     24     18    53  2.094340   
454       86248600    9680000    3886000.0     24      8    30  2.266667   
1052     108406350    9255000   31777200.0     24      9    39  3.025641   
722      288517600   32850000   15150000.0      5     19    84  4.428571   

           주말방문비율  구매주기  
cust_id                  
1269     0.000000     0  
118      0.248649     5  
2809     0.000000     0  
2620     0.595238    16  
1535     0.523810    34  
...           ...   ...  
1427     0.153846    37  
674      0.738739     6  
454      0.147059    11  
1052     0.254237     8  
722      0.309140     4  

[875 rows x 9 columns]

In [36]:
valid_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,

In [37]:
x_valid

총구매액      최대구매액         환불금액  주구매상품  주구매지점  내점일수   내점당구매건수  \
cust_id                                                                    
1269       3303000    2772000          0.0     21     15     1  5.000000   
118      228654470   30000000   45308500.0      5      3    69  2.681159   
2809       2161400    1982400          0.0      0     18     2  3.500000   
2620     140784680   32366400     667000.0      3      9    20  2.100000   
1535      27157530   14160000          0.0      5      0     7  3.000000   
...            ...        ...          ...    ...    ...   ...       ...   
1427     158728320   39960000          0.0      2      8     9  1.444444   
674      933509250  121072000  161372000.0     24     18    53  2.094340   
454       86248600    9680000    3886000.0     24      8    30  2.266667   
1052     108406350    9255000   31777200.0     24      9    39  3.025641   
722      288517600   32850000   15150000.0      5     19    84  4.428571   

           주말방문비율  구매주기  
cust_id                  
1269     0.000000     0  
118      0.248649     5  
2809     0.000000     0  
2620     0.595238    16  
1535     0.523810    34  
...           ...   ...  
1427     0.153846    37  
674      0.738739     6  
454      0.147059    11  
1052     0.254237     8  
722      0.309140     4  

[875 rows x 9 columns]

### 평가지표 확인

In [38]:
from sklearn.metrics import roc_auc_score
# help(sklearn.metrics.roc_auc_score)
# print(mean_absolute_error(y_valid, valid_pred))
print(roc_auc_score(y_valid, valid_pred))
'''
 >>> import numpy as np
    >>> from sklearn.metrics import roc_auc_score
    >>> y_true = np.array([0, 0, 1, 1])
    >>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])
    >>> roc_auc_score(y_true, y_scores)
    0.75
'''

0.5718136585143689


'\n >>> import numpy as np\n    >>> from sklearn.metrics import roc_auc_score\n    >>> y_true = np.array([0, 0, 1, 1])\n    >>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])\n    >>> roc_auc_score(y_true, y_scores)\n    0.75\n'

### 검증 모델 평가지표 확인 후 모델 결정 및 최종 test data 예측

In [39]:
test_pred = case.predict(x_test[features])

In [40]:
test_pred

array([0, 0, 0, ..., 1, 0, 0])

### 제출

In [41]:
output = pd.DataFrame({'cust_id' : x_test.cust_id,
                      'gender': test_pred})

In [42]:
output

cust_id  gender
cust_id                 
3500        3500       0
3501        3501       0
3502        3502       0
3503        3503       1
3504        3504       0
...          ...     ...
5977        5977       1
5978        5978       1
5979        5979       1
5980        5980       0
5981        5981       0

[2482 rows x 2 columns]

### 인덱스 빼고 CSV로 저장해 주기

In [43]:
output.to_csv('output.csv', index=False)

### 캐글 노트북 "Upvote"및 팔로우 클릭 부탁드립니다.
### Git 저장소 "Star"클릭 부탁드립니다.

# ※자격증 취득 이후에도 꾸준히 공부하시기 바랍니다.※